# -*- coding: utf-8 -*-
"""python3_anusha_devulapally_the_grand_master.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0-dU1J4AGP-MDY5MV9UzVfYQ93IEDhg
"""

m,n=map(int,input().split())

x,y=map(int,input().split())

tx,ty=map(int,input().split())

def isvalid(mat,x,y,m,n,t):
  #li=[]
  t=t+1
  if (((x-1)>=0 and (y-2)>=0) and mat[x-1][y-2]==0):
    mat[x-1][y-2]+=t
   # li.append((x-1,y-2))
  if (((x+1)<m and (y-2)>=0) and mat[x+1][y-2]==0):
    mat[x+1][y-2]+=t
    #li.append((x+1,y-2))
  if (((x-2)>=0 and (y-1)>=0) and mat[x-2][y-1]==0):
    mat[x-2][y-1]+=t
    #li.append((x-2,y-1))
  if (((x+2)<m and (y-1)>=0) and mat[x+2][y-1]==0):
    mat[x+2][y-1]+=t
    #li.append((x+2,y-1))
  if (((x-2)>=0 and (y+1)<n) and mat[x-2][y+1]==0):
    mat[x-2][y+1]+=t
    #li.append((x-2,y+1))
  if (((x-1)>=0 and (y+2)<n) and mat[x-1][y+2]==0):
    mat[x-1][y+2]+=t
    #li.append((x-1,y+2))
  if (((x+1)<m and (y+2)<n) and mat[x+1][y+2]==0):
    mat[x+1][y+2]+=t
    #li.append((x+1,y+2))
  if (((x+2)<m and (y+1)<n) and mat[x+2][y+1]==0):
    mat[x+2][y+1]+=t
    #li.append((x-2,y+1))

mat=[[0]*n for i in range(m)]
mat[x-1][y-1]=1
turn=1

while (mat[tx-1][ty-1]==0):
  for i in range(m):
    for j in range(n):
      if (mat[i][j]==turn):
        isvalid(mat,i,j,m,n,turn)
  turn+=1
print("minmium steps",mat[tx-1][ty-1]-1)

